#!/bin/sh

export LANG=C
export LC_ALL=C

set -e

NAME=seaweedfs
USER=${NAME}
GROUP=${NAME}

components="master volume filer s3"

case "$1" in
  purge )
    if [ -x "$(command -v deluser)" ]; then
      deluser --quiet ${USER} || \
        echo "failed to remove ${NAME} system user with deluser" 1>&2
    else
      userdel ${USER} || \
        echo "failed to remove ${NAME} system user with userdel" 1>&2
    fi
    
   
    if getent group "${GROUP}" > /dev/null; then 
      if [ -x "$(command -v delgroup)" ]; then
        delgroup --quiet --system --only-if-empty ${GROUP} || \
          echo "failed to remove ${NAME} system group with delgroup" 1>&2
      else
        groupdel ${GROUP} || \
          echo "failed to remove ${NAME} system group with groupdel" 1>&2
      fi
    fi

    for component in ${components}; do
      rm -rf \
        /var/lib/${NAME}/${component} \
        /var/log/${NAME}/${component}
    done
    ;;

  remove | upgrade | failed-upgrade )
    ;;

  abort-install | abort-upgrade | disappear )
    ;;

  * )
    echo "postrm called with unknown argument '$1'" 1>&2
    exit 1
    ;;
esac

if [ -x /usr/bin/deb-systemd-helper ]; then
  case "$1" in
    remove)
      for component in ${components}; do
        deb-systemd-helper mask   "${NAME}-${component}.service" >/dev/null || true
      done
      ;;
    purge)
      for component in ${components}; do
        deb-systemd-helper purge  "${NAME}-${component}.service" >/dev/null || true
        deb-systemd-helper unmask "${NAME}-${component}.service" >/dev/null || true
      done
      ;;
  esac
fi

exit 0

