#!/bin/sh

set -e

NAME=seaweedfs
USER=${NAME}
GROUP=${NAME}

components="master volume filer s3"

case "$1" in
  configure)
    if ! getent group "${GROUP}" > /dev/null; then
      addgroup --system --quiet "${GROUP}"
    fi

    if ! id "${USER}" > /dev/null 2>&1; then
      adduser --system --quiet \
        --home /var/lib/${NAME} \
        --no-create-home \
        --ingroup "${GROUP}" \
        --disabled-password \
        --shell /usr/sbin/nologin \
        --gecos "${NAME}" \
        "${USER}"
    fi
      
    usermod -G ${GROUP},ssl-cert "${USER}"
   
    mkdir -p /etc/${NAME}
    chmod 755 /etc/${NAME}
    chown -R root:root /etc/${NAME}

    for component in $components; do
      mkdir -p /var/lib/${NAME}/${component}
      chown -R ${USER}:${GROUP} /var/lib/${NAME}/${component}
    done
    
    for component in $components; do
      mkdir -p /var/log/${NAME}/${component}
      chown -R ${USER}:${GROUP} /var/log/${NAME}/${component}
    done
    ;;
  abort-upgrade | abort-remove | abort-deconfigure)
    ;;
  * )
    echo "postinst called with unknown argument '$1'" 1>&2
    exit 1
    ;;
esac

# Enable systemd service
if [ "$1" = "configure" ]; then
  for component in $components; do
    deb-systemd-helper enable "${NAME}-${component}.service" > /dev/null || true
    deb-systemd-helper update-state "${NAME}-${component}.service" > /dev/null || true
  done
fi

exit 0

