#!/bin/sh

set -e

export LANG=C
export LC_ALL=C

NAME=seweedfs

components="master volume filer s3"

if [ "$1" = "remove" ] && [ -d /run/systemd/system ]; then
  for component in ${components}; do
    deb-systemd-invoke stop "${NAME}-${component}" > /dev/null || true
  done
fi

exit 0

