---
- name: download srpm
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: $HOME/rpmbuild/SRPMS/
    force: no
  loop:
  - https://kojipkgs.fedoraproject.org//packages/wf-config/0.10.0/2.fc43/src/wf-config-0.10.0-2.fc43.src.rpm
  when: false

- name: install srpm
  ansible.builtin.shell: |
    rpm -vhi $HOME/rpmbuild/SRPMS/{{ item }}
  loop:
  - wf-config-0.10.0-2.fc43.src.rpm
  when: false

- block:
  - name: install build dependencies for wf-config
    ansible.builtin.shell: |
      cd /home/{{ ansible_user }}/rpmbuild/SPECS
      dnf -y builddep wf-config.spec
    become: true

- name: build wf-config
  ansible.builtin.shell: |
    cd /home/{{ ansible_user }}/rpmbuild/SPECS
    rpmbuild -bb wf-config.spec

- block:
  - name: install local wf-config package
    ansible.builtin.dnf:
      name:
      - /home/{{ ansible_user }}/rpmbuild/RPMS/x86_64/wf-config-0.10.0-2.el10.x86_64.rpm
      - /home/{{ ansible_user }}/rpmbuild/RPMS/x86_64/wf-config-devel-0.10.0-2.el10.x86_64.rpm
      state: present
      disable_gpg_check: true
    become: true

