---
- name: download wayfire srpm
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: $HOME/rpmbuild/SRPMS/
    force: no
  loop:
  - https://kojipkgs.fedoraproject.org//packages/wayfire/0.10.1/1.fc43/src/wayfire-0.10.1-1.fc43.src.rpm
  when: false

- name: install srpm
  ansible.builtin.shell: |
    rpm -vhi $HOME/rpmbuild/SRPMS/{{ item }}
  loop:
  - wayfire-0.10.1-1.fc43.src.rpm
  when: false


- block:
  - name: install build dependencies for wayfire
    ansible.builtin.shell: |
      cd /home/{{ ansible_user }}/rpmbuild/SPECS
      dnf -y builddep wayfire.spec
    become: true

- name: build rpm package
  ansible.builtin.shell: |
    cd $HOME/rpmbuild/SPECS
    rpmbuild -bb wayfire.spec

- block:
  - name: install local wayfire package
    ansible.builtin.dnf:
      name:
      - /home/{{ ansible_user }}/rpmbuild/RPMS/x86_64/wayfire-0.10.1-1.el10.x86_64.rpm
      state: present
      disable_gpg_check: true
    become: true

