---
- name: download srpm
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ ansible_user_home }}/rpmbuild/SRPMS/"
    force: no
  loop:
  - "{{ glm_url }}"
  become: false

- name: install srpm
  ansible.builtin.shell: |
    rpm -vhi {{ ansible_user_home }}/rpmbuild/SRPMS/{{ item }}
  loop:
  - "{{ glm_srpm }}"
  become: false

- block:
  - name: install build dependencies for glm
    ansible.builtin.shell: |
      cd {{ ansible_user_home }}/rpmbuild/SPECS
      dnf -y builddep glm.spec
    become: true

- name: build glm
  ansible.builtin.shell: |
    cd {{ ansible_user_home }}/rpmbuild/SPECS
    rpmbuild -bb glm.spec
  become: false

- block:
  - name: install local glm package
    ansible.builtin.dnf:
      name: "{{ ansible_user_home }}/rpmbuild/RPMS/noarch/{{ glm_devel_rpm }}"
      state: present
      disable_gpg_check: true
    become: true

