---
- name: download srpm
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ ansible_user_home }}/rpmbuild/SRPMS/"
    force: no
  loop:
  - "{{ target_url }}"

- name: install srpm
  ansible.builtin.shell: |
    rpm -vhi {{ ansible_user_home }}/rpmbuild/SRPMS/{{ item }}
  loop:
  - "{{ target_srpm }}"


- block:
  - name: install build dependencies
    ansible.builtin.shell: |
      cd {{ ansible_user_home }}/rpmbuild/SPECS
      dnf -y builddep {{ target_spec }}
    become: true

- name: build rpm package
  ansible.builtin.shell: |
    cd {{ ansible_user_home }}/rpmbuild/SPECS
    rpmbuild -bb {{ target_spec }}

- block:
  - name: install local package
    ansible.builtin.dnf:
      name: "{{ target_rpms }}"
      state: present
      disable_gpg_check: true
    become: true
    tags: install, never

