#!/bin/sh

version="0.0.4"

flags=""
args=""
configfile=""

show_version()
{
  echo "pcapd $version"
}

while [ "$#" -ne 0 ]; do
  case $1 in
    -h )
      ;;
    -c | --config)
      shift
      configfile="$1"
      ;;
    -v | --version)
      show_version
      exit 0
      ;;
    -* )
      shift
      flags="$flags $1"
      ;;
    * )
      args="$args $1"
      ;;
  esac
  
  shift
done

if [ -z "$configfile" ]; then
  . $configfile
fi

umask 0002

exec tcpdump \
  ${PCAPD_IF_OPTION} \
  ${PCAPD_ROTATE} \
  ${PCAPD_USER_OPTION} \
  ${PCAPD_OUTPUT_OPTION} \
  ${PCAPD_POSTROTATE_CMD_OPTION} \
  ${flags}


