#!/bin/sh

version="0.0.6"

flags=""
args=""
configfile=""
iface=""

show_version()
{
  echo "pcapd $version"
}

while [ "$#" -ne 0 ]; do
  case $1 in
    -h )
      ;;
    -c | --config)
      shift
      configfile="$1"
      ;;
    -v | --version)
      show_version
      exit 0
      ;;
    -* )
      shift
      flags="$flags $1"
      ;;
    * )
      iface="$1"
      ;;
  esac
  
  shift
done

if [ -z "$iface" ]; then
  echo "ERROR: no interface instance"
  exit 1
fi

PCAPD_IF="$iface"

if [ ! -z "$configfile" ]; then
  . $configfile
fi

umask 0002

exec tcpdump \
  -i ${PCAPD_IF} \
  ${PCAPD_ROTATE_OPTION} \
  ${PCAPD_USER_OPTION} \
  ${PCAPD_OUTPUT_OPTION} \
  ${PCAPD_POSTROTATE_CMD_OPTION} \
  ${flags}


