#!/bin/sh

pcapmv_conf="/etc/pcapd/pcapmv.conf"

if [ -f "$pcapmv_conf" ]; then
  . $pcapmv_conf
else
  echo "ERROR: no such file, $pcapmv_conf" 1>&2
  exit 1
fi

if [ -z "${PCAPMV_SRCDIR}" ]; then
  PCAPMV_SRCDIR="/var/lib/pcapd"
fi

if [ -z "${PCAPMV_DSTDIR}" ]; then
  PCAPMV_DSTDIR="/home/pcapd/pcapd"
fi

main()
{
  echo "DEBUG: This is main function in $0" 1>&2
  mkdir -p ${PCAPMV_DSTDIR}
  find "${PCAPMV_SRCDIR}" -type f -name "*.pcap.xz" -print | \
    xargs -0 -I{} sh $0 {}
  
  # remove empty directory
  find ${PCAPMV_SRCDIR} -depth -type d -empty -delete
}

move_pcap()
{
  src="$1" 
  echo "DEBUG: src is $src" 1>&2
  echo "DEBUG: This is sub function in $0" 1>&2

  base=`basename $src`
  echo $base | grep -E "^[0-9]{8}-[0-9]{2}" >/dev/null
  if [ "$?" -ne 0 ]; then
     echo "ERROR: invalid basename, $src" 1>&2
	 exit 1
  else
     echo "DEBUG: basename, $base" 1>&2
  fi

  year=`echo $base | sed -E -e "s/^([[:digit:]]{4})(.*)/\1/"`
  month=`echo $base | sed -E -e "s/^([[:digit:]]{4})([[:digit:]]{2})(.*)/\2/"`
  day=`echo $base | sed -E -e "s/^([[:digit:]]{6})([[:digit:]]{2})(.*)/\2/"`
  daydir=`echo $base | sed -E -e "s/^([[:digit:]]{8})-(.*)/\1/"`
  hour=`echo $base | sed -E -e "s/^([[:digit:]]{8})-([[:digit:]]{2})(.*)/\2/"`
  hourdir=`echo $base | sed -E -e "s/^([[:digit:]]{8}-[[:digit:]]{2})(.*)/\1/"`

  #echo "YEAR: $year"
  #echo "MONTH: $month"
  #echo "DAY: $day"
  #echo "HOUR: $hour"

  ym="${year}${month}"
  ymd="${year}${month}${day}"
  ymd_h="${year}${month}${day}-${hour}"
  dstdir="${PCAPMV_DSTDIR}/${ym}/${ymd}/${ymd}-${hour}"
  dst="$dstdir/${base}"
  echo "DEBUG: $src -> $dst" 1>&2
  mv -f "$src" "$dst"
}

targets=""

while [ "$#" -ne 0 ]; do
  case $1 in
    -h )
	  ;;
	-- )
	  break
	  ;;
	* )
	  targets="$targets $1"
	  ;;
  esac
  
  shift
done

if [ -z "$targets" ]; then
  # no argument
  main 
  exit
fi

for target in $targets; do
  move_pcap "$target" "$dsttop"
done

#for target in $targets; do
#  target=`echo $target | tr '-' '_'`
#  num=`LANG=C type $target | grep 'function' | wc -l`
#  if [ "$num" -ne 0 ]; then
#    $target
#  else
#    echo "ERROR: no such target, $target" 1>&2
#  fi
#done



