#!/bin/sh

#set -e

PKG_NAME=pcapd
PKG_USER=pcapd
PKG_GROUP=pcapd

case "$1" in
  configure)
    num=`getent group | grep -e "^${PKG_GROUP}:" | wc -l`
    if [ "$num" -eq 0 ]; then
      LANG=C addgroup --system --quiet "${PKG_GROUP}"
    fi

    num=`getent passwd | grep -e "^${PKG_USER}:" | wc -l`
    if [ "$num" -eq 0 ]; then
      LANG=C adduser --system --quiet \
        --home /home/${PKG_NAME} \
        --ingroup "${PKG_GROUP}" \
        --disabled-password \
        --shell /bin/bash \
        --gecos ${PKG_USER} \
        "${PKG_USER}"
    fi
    
    mkdir -p /etc/${PKG_NAME}
    chown -R "${PKG_USER}:${PKG_GROUP}" /etc/${PKG_NAME}
    chmod -R 0755 /etc/${PKG_NAME}/
    
    mkdir -p /var/lib/${PKG_NAME}
    chown -R "${PKG_USER}:${PKG_GROUP}" /var/lib/${PKG_NAME}
    chmod u+rwx /var/lib/${PKG_NAME}
    
    mkdir -p /var/log/${PKG_NAME}
    chown -R "${PKG_USER}:${PKG_GROUP}" /var/log/${PKG_NAME}
    chmod u+rwx /var/log/${PKG_NAME}
    
    mkdir -p /var/cache/${PKG_NAME}
    chown -R "${PKG_USER}:${PKG_GROUP}" /var/cache/${PKG_NAME}
    chmod -R 750 /var/cache/${PKG_NAME}

    if [ -d "/var/run/${PKG_NAME}" ]; then
      chown -R "${PKG_USER}:${PKG_GROUP}" /var/run/${PKG_NAME}
      chmod -R 750 /var/run/${PKG_NAME}
    fi


    # enable /etc/apparmor.d/local/usr.bin.tcpdump
    sed -i -E -e 's|^(\s*)#(include <local/usr.bin.tcpdump>)|\1\2|' /etc/apparmor.d/usr.bin.tcpdump

    systemctl restart apparmor

    systemctl restart cron

    ;;
  abort-upgrade | abort-remove | abort-deconfigure)
    ;;
  * )
    echo "postinst called with unknown argument '$1'" 1>&2
    exit 1
    ;;
esac

case "$1" in
  configure | abort-upgrade | abort-deconfigure | abort-remove )
    units=`systemctl list-unit-files "${PKG_NAME}@*.service" --no-legend \
      | awk '{ print $1 }'`

    for unit in $units; do
      deb-systemd-helper unmask "$units" \
        > /dev/null 2>&1 || true
    done

    if deb-systemd-helper --quiet was-enabled "${PKG_NAME}"; then
      deb-systemd-helper enable       "${PKG_NAME}" > /dev/null 2>&1 || true
    else
      deb-systemd-helper update-state "${PKG_NAME}" > /dev/null 2>&1 || true
    fi
    ;;
  * )
    ;;
esac

exit 0

