#!/bin/sh

set -e

PKG_NAME=pcapd
PKG_USER=pcapd
PKG_GROUP=pcapd

case "$1" in
  configure)
    echo "DEBUG: configure in postinst" 1>&2
    echo "DEBUG: getent group ${PKG_GROUP}"
    #getent group "${PKG_GROUP}" > /dev/null
    num=`getent group | grep -e "^${PKG_GROUP}:" | wc -l`
    if [ "$num" -eq 0 ]; then
      echo "DEBUG: addgroup --system --quiet ${PKG_GROUP}"
      addgroup --system --quiet "${PKG_GROUP}"
    fi

    echo "DEBUG: id ${PKG_USER}"
    num=`getent passwd | grep -e "^${PKG_USER}:" | wc -l`
    if [ "$num" -eq 0 ]; then
      echo "DEBUG: adduser --system --quiet"
      adduser --system --quiet \
        --home /var/lib/${PKG_NAME} \
        --no-create-home \
        --ingroup "${PKG_GROUP}" \
        --disabled-password \
        --shell /usr/sbin/nologin \
        --gecos ${PKG_USER} \
        "${PKG_USER}"
    fi
    
    mkdir -p /etc/${PKG_NAME}
    chown -R "${PKG_USER}:${PKG_GROUP}" /etc/${PKG_NAME}
    chmod -R 0755 /etc/${PKG_NAME}/
    
    mkdir -p /var/lib/${PKG_NAME}
    chown -R "${PKG_USER}:${PKG_GROUP}" /var/lib/${PKG_NAME}
    chmod u+rwx /var/lib/${PKG_NAME}
    
    mkdir -p /var/log/${PKG_NAME}
    chown -R "${PKG_USER}:${PKG_GROUP}" /var/log/${PKG_NAME}
    chmod u+rwx /var/log/${PKG_NAME}
    
    mkdir -p /var/cache/${PKG_NAME}
    chown -R "${PKG_USER}:${PKG_GROUP}" /var/cache/${PKG_NAME}
    chmod -R 750 /var/cache/${PKG_NAME}

    if [ -d "/var/run/${PKG_NAME}" ]; then
      chown -R "${PKG_USER}:${PKG_GROUP}" /var/run/${PKG_NAME}
      chmod -R 750 /var/run/${PKG_NAME}
    fi

    # enable /etc/apparmor.d/local/usr.bin.tcpdump
    sed -i -E -e 's|^(\s*)#(include <local/usr.bin.tcpdump>)|\1\2|' /etc/apparmor.d/usr.bin.tcpdump

    systemctl restart apparmor

    ;;
  abort-upgrade | abort-remove | abort-deconfigure)
    ;;
  * )
    echo "postinst called with unknown argument '$1'" 1>&2
    exit 1
    ;;
esac

case "$1" in
  configure | abort-upgrade | abort-deconfigure | abort-remove )
    echo "DEBUG: deb-systemd-helper umask"
    deb-systemd-helper umask "${PKG_NAME}.service" > /dev/null || true

    echo "DEBUG: deb-systemd-helper was-enabled"
    if deb-systemd-helper --quiet was-enabled "${PKG_NAME}"; then
      deb-systemd-helper enable       "${PKG_NAME}" > /dev/null || true
    else
      echo "DEBUG: deb-systemd-helper update-state"
      deb-systemd-helper update-state "${PKG_NAME}" > /dev/null || true
    fi
    ;;
  * )
    ;;
esac

exit 0

