#!/bin/sh

set -e

PKG_NAME=pcapd

if [ "$1" = "remove" ] && [ -d /run/systemd/system ]; then
  units=`systemctl list-unit-files "${PKG_NAME}@*.service" --no-legend \
      | awk '{ print $1 }'`
  for unit in $units; do
    deb-systemd-invoke stop "$unit" > /dev/null || true
  done
fi

exit 0

