LISTEN_URL="https://localhost:5555"
ISSUER_URL="https://localhost:5556/dex"
REDIRECT_URI="https://localhost:5555/callback"
TLS_CERT="/etc/dex/certs/example-app.crt"
TLS_KEY="/etc/dex/certs/example-app.key"

