---
- name: download srpm
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ ansible_user_home }}/rpmbuild/SRPMS/"
    force: no
  loop:
  - "{{ wf_config_url }}"

- name: install srpm
  ansible.builtin.shell: |
    rpm -vhi {{ ansible_user_home }}/rpmbuild/SRPMS/{{ item }}
  loop:
  - "{{ wf_config_srpm }}"

- block:
  - name: install build dependencies for wf-config
    ansible.builtin.shell: |
      cd /home/{{ ansible_user }}/rpmbuild/SPECS
      dnf -y builddep wf-config.spec
    become: true

- name: build wf-config
  ansible.builtin.shell: |
    cd /home/{{ ansible_user }}/rpmbuild/SPECS
    rpmbuild -bb wf-config.spec
  become: false

- block:
  - name: install local wf-config package
    ansible.builtin.dnf:
      name:
      - "{{ ansible_user_home }}/rpmbuild/RPMS/x86_64/{{ wf_config_rpm }}"
      - "{{ ansible_user_home }}/rpmbuild/RPMS/x86_64/{{ wf_config_devel_rpm }}"
      state: present
      disable_gpg_check: true
    become: true

